baseURL = "http://example.org/"
title = "MRiveraLanas"
theme = "hugo-coder"


[params]
  author = "MergeConflict"
  info = "Thoughts and investigations about the technologies changing our society and the institutions behind them. And other reflections"
  description = ""
  keywords = "blog,developer,personal"
  avatarURL = "images/gitmergeconflict_3.jpg"


[[menu.main]]
  name = "Blog"
  weight = 3
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 3
  url = "about/"
[[menu.main]]
  name = "What I'm Reading"
  weight = 3
  url = "reading/"
[[menu.main]]
  name = "Hugo FAQ (by me)"
  weight = 3
  url = "hugo-questions/"



[taxonomies]
  tag = "tags"


